version: "3.9"
services:
  backend:
    container_name: plantbackend
    build: Backend/
    ports:
      - 8000:8000
    networks:
      - plantleaf-app
  frontend:
    container_name: plantfrontend
    build: Frontend/
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    ports:
      - 3000:3000
    networks:
      - plantleaf-app
networks:
  plantleaf-app:
    driver: bridge
